google:
  email: "student2137@school.edu"
  passwd: "aaaaaaaa"
  perform_auto_login: no
librus:
  email: "paul.jumper@gmail.com"
  passwd: "aaaaaaaa"
chrome:
  args:
    - 'user-data-dir=./profile'
    - '--window-size=1800,800'
  experimental:
    - name: useAutomationExtension
      value: False
    - name: excludeSwitches
      value: ['enable-automation']